ts-node ./migrations/add-private-field-to-groups
ts-node ./migrations/migrate-dependants
ts-node ./migrations/update-admin-approval-emails
ts-node ./migrations/update-user-emails
ts-node ./migrations/add-orgId-to-attestations
ts-node ./migrations/relocate-auth-id
ts-node ./migrations/remove-admin-auth-id
ts-node ./migrations/update-organizationids-for-users
ts-node ./migrations/trim-firstname-lastname-and-fix-last-name
ts-node ./migrations/add-questionnaireid-to-attestation
ts-node ./migrations/test-results-to-pcr
ts-node ./migrations/acuity-to-appointments
ts-node ./migrations/acuity-to-pcr-results
