openapi: 3.0.1
info:
  title: Reservation API
  version: 1.0.0
components:
  schemas:
    AppointmentResponse200:
      type: object
      additionalProperties: false
      properties:
        data:
          type: object
          additionalProperties: false
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
              format: email
          required:
            - firstName
            - lastName
            - email
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                    succeed,
                    failed,
                    validation_error,
                    internal_server_error,
                    unauthorized,
                    access_denied,
                    resource_not_found,
                ]
            message:
              nullable: true
              type: string
    Response:
      type: object
      additionalProperties: false
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                    succeed,
                    failed,
                    validation_error,
                    internal_server_error,
                    unauthorized,
                    access_denied,
                    resource_not_found,
                ]
            message:
              nullable: true
              type: string


paths:
  /admin/page/next-bar-code:
    get:
      description: Show Next Bar Code
      parameters:
        - in: query
          name: newcode
          schema:
            type: integer
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/send-single-results:
    get:
      description: Form to Send Single Results
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/send-bulk-results:
    get:
      description: Form to Send Bulk Results
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/appointment-by-bar-code:
    get:
      description: Show Form to Enter Bar Code
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string
    post:
      description: Show Appoinment Details
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/appointment:
    post: #Post is used to avoid sending PI info to access logs
      description: Get Appoinment for Bar Code
      requestBody:
        content:
          application/json:
            schema:
              properties:
                barCode:
                  type: string
              required:
                - barCode
              example: {barCode: "X0000000000"}

      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse200'

  /admin/api/v1/send-and-save-test-results:
    post:
      description: Save and Send Single Results
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCode:
                  type: string
                result:
                  type: string
                  enum:
                    - Positive
                    - Negative
                famEGene:
                  type: string
                famCt:
                  type: string
                calRed61RdRpGene:
                  type: string
                calRed61Ct:
                  type: string
                quasar670NGene:
                  type: string
                quasar670Ct:
                  type: string
                hexIC:
                  type: string
                hexCt:
                  type: string
                needConfirmation:
                  type: boolean
              required:
                - barCode
                - result
                - famEGene
                - famCt
                - calRed61RdRpGene
                - calRed61Ct
                - quasar670NGene
                - quasar670Ct
                - hexIC
                - hexCt
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/send-test-results-again:
    post:
      description: Send Results Again
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCode:
                  type: string
              required:
                - barCode
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /webhook/acuity/schedule:
    post:
      description: Webhook for adding barcode to acuity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              properties:
                calendarID:
                  type: string
                appointmentTypeID:
                  type: string
                action:
                  type: string
                id:
                  type: string
      responses:
        '200':
          description: Successfully handled
          content:
            text/html:
              schema:
                type: string

  /admin/js/print-label.js:
    get:
      description: Show JS for printing
      responses:
        '200':
          description: Successfully Return
          content:
            text/javascript:
              schema:
                type: string

  /admin/js/print-label-library.js:
    get:
      description: Show JS Library for printing
      responses:
        '200':
          description: Successfully Return
          content:
            text/javascript:
              schema:
                type: string
