openapi: 3.0.1
info:
  title: Reservation API
  version: 1.0.0
components:
  schemas:
    AppointmentResponse200:
      type: object
      additionalProperties: false
      properties:
        data:
          type: object
          additionalProperties: false
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
              format: email
          required:
            - firstName
            - lastName
            - email
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string
    Response:
      type: object
      additionalProperties: false
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

paths:
  /admin/page/next-bar-code:
    get:
      description: Show Next Bar Code 
      parameters:
        - in: query
          name: newcode
          schema:
            type: integer
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string
  /admin/page/appointment-by-bar-code:
    get:
      description: Show Form to Enter Bar Code
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string
    post:
      description: Show Appoinment Details
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/appointment:
    post: #Post is used to avoid sending PI info to access logs
      description: Get Appoinment for Bar Code  
      requestBody:
        content:
          application/json:
            schema:
              properties:
                barCode:
                  type: string
              required:
                - barCode
              example: {barCode: "X0000000000"}

      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse200'

  /admin/js/print-label.js:
    get:
      description: Show JS for printing
      responses:
        '200':
          description: Successfully Return
          content:
            text/javascript:
              schema:
                type: string
                