openapi: 3.0.1
info:
  title: Reservation API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TestResult200:
      type: object
      deprecated: false
      additionalProperties: false
      properties:
        id:
          type: number
        firstName:
          type: string
        lastName:
          type: string
        testType:
          type: string
        dateOfAppointment:
          type: string
        result:
          type: string

    AppointmentResponse200:
      type: object
      additionalProperties: false
      properties:
        data:
          type: object
          additionalProperties: false
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
              format: email
          required:
            - firstName
            - lastName
            - email
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                    succeed,
                    failed,
                    validation_error,
                    internal_server_error,
                    unauthorized,
                    access_denied,
                    resource_not_found,
                ]
            message:
              nullable: true
              type: string
    Response:
      type: object
      additionalProperties: false
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                    succeed,
                    failed,
                    validation_error,
                    internal_server_error,
                    unauthorized,
                    access_denied,
                    resource_not_found,
                ]
            message:
              nullable: true
              type: string


paths:
  /admin/page/next-bar-code:
    get:
      description: Show Next Bar Code
      parameters:
        - in: query
          name: newcode
          schema:
            type: integer
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/send-single-results:
    get:
      description: Form to Send Single Results
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/send-bulk-results:
    get:
      description: Form to Send Bulk Results
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/send-fax-for-positive:
    get:
      description: Form to Send Fax for Positive results
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/page/appointment-by-bar-code:
    get:
      description: Show Form to Enter Bar Code
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string
    post:
      description: Show Appoinment Details
      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/appointment:
    post: #Post is used to avoid sending PI info to access logs
      description: Get Appoinment for Bar Code
      requestBody:
        content:
          application/json:
            schema:
              properties:
                barCode:
                  type: string
              required:
                - barCode
              example: { barCode: "X0000000000" }

      responses:
        '200':
          description: Successfully Return Appoinment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse200'

  /admin/api/v1/send-and-save-test-results-bulk:
    post:
      description: Save and Send Single Results
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                from:
                  type: string
                to:
                  type: string
                resultDate:
                  type: string
                results:
                  type: array
                  items:
                      type: object
                      properties:
                        barCode:
                          type: string
                        result:
                          type: string
                          enum:
                            - Positive
                            - Negative
                            - 2019-nCoV Detected
                        famEGene:
                          type: string
                        famCt:
                          type: string
                        calRed61RdRpGene:
                          type: string
                        calRed61Ct:
                          type: string
                        quasar670NGene:
                          type: string
                        quasar670Ct:
                          type: string
                        hexIC:
                          type: string
                        hexCt:
                          type: string
              required:
                - from
                - to
                - results
                - resultDate
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/send-and-save-test-results:
    post:
      description: Save and Send Single Results
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCode:
                  type: string
                result:
                  type: string
                  enum:
                    - Positive
                    - Negative
                    - 2019-nCoV Detected
                famEGene:
                  type: string
                famCt:
                  type: string
                calRed61RdRpGene:
                  type: string
                calRed61Ct:
                  type: string
                quasar670NGene:
                  type: string
                quasar670Ct:
                  type: string
                hexIC:
                  type: string
                hexCt:
                  type: string
                needConfirmation:
                  type: boolean
                resultDate:
                  type: string
              required:
                - barCode
                - result
                - famEGene
                - famCt
                - calRed61RdRpGene
                - calRed61Ct
                - quasar670NGene
                - quasar670Ct
                - hexIC
                - hexCt
                - resultDate
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/send-fax-for-positive:
    post:
      description: Send Fax for positive result
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCode:
                  type: string
                faxNumber:
                  type: string
              required:
                - barCode
                - faxNumber
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/send-test-results-again:
    post:
      description: Send Results Again
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCode:
                  type: string
                result:
                  type: string
                  enum:
                    - Positive
                    - Negative
                    - 2019-nCoV Detected
                famEGene:
                  type: string
                famCt:
                  type: string
                calRed61RdRpGene:
                  type: string
                calRed61Ct:
                  type: string
                quasar670NGene:
                  type: string
                quasar670Ct:
                  type: string
                hexIC:
                  type: string
                hexCt:
                  type: string
                needConfirmation:
                  type: boolean
                resultDate:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                dateOfBirth:
                  type: string
                registeredNursePractitioner:
                  type: string
                dateOfAppointment:
                  type: string
                appointmentId:
                  type: string
                timeOfAppointment:
                  type: string
                id:
                  type: string
                packageCode:
                  type: string
                timestamps:
                  type: string
              required:
                - barCode
                - result
                - famEGene
                - famCt
                - calRed61RdRpGene
                - calRed61Ct
                - quasar670NGene
                - quasar670Ct
                - hexIC
                - hexCt
                - resultDate
                - firstName
                - lastName
                - email
                - phone
                - dateOfBirth
                - registeredNursePractitioner
                - dateOfAppointment
                - appointmentId
                - timeOfAppointment
                - id
                - packageCode
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /admin/api/v1/check-appointments:
    post:
      description: Check appointments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                barCodes:
                  type: array
                  items:
                    type: string
              required:
                - barCodes
      responses:
        '200':
          description: Successfully Return
          content:
            text/html:
              schema:
                type: string

  /webhook/acuity/schedule:
    post:
      description: Webhook for adding barcode to acuity
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              additionalProperties: true
              properties:
                calendarID:
                  type: string
                appointmentTypeID:
                  type: string
                action:
                  type: string
                id:
                  type: string
      responses:
        '200':
          description: Successfully handled
          content:
            text/html:
              schema:
                type: string

  /admin/js/print-label.js:
    get:
      description: Show JS for printing
      responses:
        '200':
          description: Successfully Return
          content:
            text/javascript:
              schema:
                type: string

  /admin/js/print-label-library.js:
    get:
      description: Show JS Library for printing
      responses:
        '200':
          description: Successfully Return
          content:
            text/javascript:
              schema:
                type: string

  /reservation/admin/api/v1/test-results:
    get:
      description: Get test results by organization ID
      parameters:
        - in: query
          name: organizationId
          schema:
            type: string
        - in: query
          name: dateOfAppointment
          schema:
            type: string
      responses:
        '200':
          description: Successfully Return
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResult200'

  /reservation/admin/api/v1/appointments:
    get:
      description: Get appointmenr list by organization ID
      security:
        - bearerAuthJWT: []
      parameters:
        - in: query
          name: organizationId
          schema:
            type: string
        - in: query
          name: searchQuery
          schema:
            type: string
        - in: query
          name: dateOfAppointment
          schema:
            type: string
      responses:
        '200':
          description: Successfully Return
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppointmentResponse200'

  /reservation/admin/api/v1/appointments/{appointmentId}:
    get:
      description: Get appointment by appointment ID
      parameters:
        - in: path
          name: appointmentId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully Return
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse200'

  /reservation/admin/api/v1/packages:
    post:
      description: Add Package Codes for Orgs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                packageCode:
                  type: string
                organizationId:
                  type: string
              required:
                - packageCode
                - organizationId
      responses:
        '200':
          description: Successfully handled
          content:
            text/html:
              schema:
                type: string

  /reservation/admin/api/v1/appointments/{appointmentId}/cancel:
    put:
      description: Cancel appointment by appointment ID
      security:
        - bearerAuthJWT: []
      parameters:
        - in: path
          name: appointmentId
          schema:
            type: number
          required: true
        - in: query
          name: organizationId
          schema:
            type: string
      responses:
        '200':
          description: Successfully Return
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse200'
