openapi: 3.0.1
info:
  title: Access API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Response:
      type: object
      additionalProperties: false
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    Access:
      type: object
      additionalProperties: false
      properties:
        token:
          type: string
        userId:
          type: string
        statusToken:
          type: string
        locationId:
          type: string
        createdAt:
          type: string
        enteredAt:
          type: string
          nullable: true
        exitAt:
          type: string
          nullable: true
        includesGuardian:
          type: boolean
        dependants:
          type: object
          additionalProperties:
            type: object
            additionalProperties: false
            properties:
              id:
                type: string
              enteredAt:
                type: string
                nullable: true
              exitAt:
                type: string
                nullable: true


    Passport:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        statusToken:
          type: string
        status:
          type: string
          enum: [pending,proceed,caution,stop]
        validFrom:
          type: string
        validUntil:
          type: string

    EntryOrExitRequest:
      type: object
      additionalProperties: false
      properties:
        accessToken:
          type: string
        userId:
          type: string
      required:
        - accessToken
        - userId

    SelfEntryOrExitRequest:
      type: object
      additionalProperties: false
      properties:
        organizationId:
          type: string
        locationId:
          type: string
        accessToken:
          type: string
      required:
        - organizationId
        - locationId
        - accessToken

    StatusTokenExchangeRequest:
      type: object
      additionalProperties: false
      properties:
        statusToken:
          type: string
        locationId:
          type: string
        userId:
          type: string
        includeGuardian:
          type: boolean
        dependantIds:
          type: array
          items:
            type: string
      required:
        - statusToken
        - locationId
        - userId
        - includeGuardian

    Statistics:
      type: object
      additionalProperties: false
      properties:
        peopleOnPremises:
          type: number
        accessDenied:
          type: number
        asOfDateTime:
          type: string
          description: ISO date (eg. "2020-08-27T13:45:00.141Z")
        exposures:
          type: number
          description: Number of exposures
        pendingPassports:
          type: number
          description: Number of pending passports
        proceedPassports:
          type: number
          description: Number of proceed passports
        cautionPassports:
          type: number
          description: Number of caution passports
        stopPassports:
          type: number
          description: Number of stop passports
        checkInsPerHour:
          type: array
          items:
            type: object
            additionalProperties: false
            properties:
              date:
                type: string
                description: ISO date (eg. "2020-08-27T13:45:00.141Z")
              count:
                type: number
                description: Number of check-ins at the given time

    ResponseOfAccess:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/Access'
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    ResponseOfPassport:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/Passport'
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string


    ResponseOfStatistics:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/Statistics'
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    ResponseOfEnterOrExit:
      type: object
      additionalProperties: false
      properties:
        data:
          type: object
          additionalProperties: false
          properties:
            passport:
              $ref: '#/components/schemas/Passport'
            base64Photo:
              type: string
            includesGuardian:
              type: boolean
            firstName:
              type: string
            lastName:
              type: string
            dependants:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
            access:
              $ref: '#/components/schemas/Access'
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

  responses:
    Response:
      description: Default Response wrapper
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
paths:
  /setTime:
    post:
      description: set the time on the server. Onlyu works on local servers in guilible mode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  milliseconds:
                    type: number
      responses:
        '200':
          description: Successfully set

  /user/createToken:
    post:
      description: Exchange status-token for an access-token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusTokenExchangeRequest'
      responses:
        '200':
          description: Successfully exchanged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfAccess'

  /admin/createToken:
    post:
      description: Exchange status-token for an access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusTokenExchangeRequest'
      responses:
        '200':
          description: Successfully exchanged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfAccess'

  /admin/{organizationId}/locations/accessible:
    get:
      description: Get locations for quick checkins
      parameters:
        - in: path
          name: organizationId
          schema:
            type: string
          required: true
        - in: query
          name: userId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfully returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
  /admin/enter:
    post:
      description: Handle user's entrance with access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /admin/exit:
    post:
      description: Handle user's exit with access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /admin/stats:
    post:
      description: Daily and live stats for a location
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                locationId:
                  type: string
              required:
                - locationId
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfStatistics'

  /admin/stats/v2:
    post:
      description: Daily and live location stats
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                organizationId:
                  type: string
                locationId:
                  type: string
              required:
                - organizationId
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfStatistics'

  /user/enter:
    post:
      description: Handle self user's entrance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfEntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /triggerReports:
    get:
      description: Triggers reports to be sent for the current hour. Likely to become inaccessible except via cron. This is a GET request with side effects, be cautious!
      responses:
        '200':
          description: Success

  /requestTrace:
    post:
      description: Triggers a contact trace on a user. Likely to become inaccessible except via pubsub
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                message:
                  type: object
                  additionalProperties: false
                  properties:
                    data:
                      type: string
                      description: The base64 encoding of the payload

      responses:
        '200':
          description: Success

  /user/exit:
    post:
      description: Handle self user's exit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfEntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'
