openapi: 3.0.1
info:
  title: Access API
  version: 1.0.0
components:
  schemas:
    Response:
      type: object
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    Access:
      type: object
      properties:
        token:
          type: string
        createdAt:
          type: string

    ResponseOfAccess:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Access'
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

  responses:
    Response:
      description: Default Response wrapper
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
paths:
  /user/createToken:
    post:
      description: Exchange status-token for an access-token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                statustoken:
                  type: string
              required:
                - statusToken

      responses:
        '200':
          description: Successfully exchanged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfAccess'
