openapi: 3.0.1
info:
  title: Access API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Response:
      type: object
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    Access:
      type: object
      properties:
        token:
          type: string
        userId:
          type: string
        statusToken:
          type: string
        locationId:
          type: string
        createdAt:
          type: string
        enteredAt:
          type: string
          nullable: true
        exitAt:
          type: string
          nullable: true
        includesGuardian:
          type: boolean
        dependants:
          type: object
          additionalProperties:
            type: object
            properties:
              id:
                type: string
              enteredAt:
                type: string
                nullable: true
              exitAt:
                type: string
                nullable: true


    Passport:
      type: object
      properties:
        id:
          type: string
        statusToken:
          type: string
        status:
          type: string
          enum: [pending,proceed,caution,stop]
        validFrom:
          type: string
        validUntil:
          type: string

    EntryOrExitRequest:
      type: object
      properties:
        accessToken:
          type: string
        userId:
          type: string
      required:
        - accessToken
        - userId

    SelfEntryOrExitRequest:
      type: object
      properties:
        organizationId:
          type: string
        locationId:
          type: string
        accessToken:
          type: string
      required:
        - organizationId
        - locationId
        - accessToken

    StatusTokenExchangeRequest:
      type: object
      properties:
        statusToken:
          type: string
        locationId:
          type: string
        userId:
          type: string
        includeGuardian:
          type: boolean
          description: In this version, this argument has no effect. Guardians are never included if the access includes dependants
        dependantIds:
          type: array
          items:
            type: string
        delegateAdminUserId:
          type: string
      required:
        - statusToken
        - locationId
        - userId

    Statistics:
      type: object
      properties:
        peopleOnPremises:
          type: number
        accessDenied:
          type: number
        asOfDateTime:
          type: string
          description: ISO date (eg. "2020-08-27T13:45:00.141Z")
        exposures:
          type: number
          description: Number of exposures
        pendingPassports:
          type: number
          description: Number of pending passports
        proceedPassports:
          type: number
          description: Number of proceed passports
        cautionPassports:
          type: number
          description: Number of caution passports
        stopPassports:
          type: number
          description: Number of stop passports
        checkInsPerHour:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                description: ISO date (eg. "2020-08-27T13:45:00.141Z")
              count:
                type: number
                description: Number of check-ins at the given time

    ResponseOfAccess:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Access'
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    ResponseOfPassport:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Passport'
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string


    ResponseOfStatistics:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Statistics'
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    ResponseOfEnterOrExit:
      type: object
      properties:
        data:
          type: object
          properties:
            passport:
              $ref: '#/components/schemas/Passport'
            base64Photo:
              type: string
            includesGuardian:
              type: boolean
            firstName:
              type: string
            lastName:
              type: string
            dependants:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

  responses:
    Response:
      description: Default Response wrapper
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
paths:
  /user/createToken:
    post:
      description: Exchange status-token for an access-token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusTokenExchangeRequest'
      responses:
        '200':
          description: Successfully exchanged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfAccess'

  /admin/createToken:
    post:
      description: Exchange status-token for an access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusTokenExchangeRequest'
      responses:
        '200':
          description: Successfully exchanged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfAccess'

  /admin/{organizationId}/locations/accessible:
    get:
      description: Get locations for quick checkins
      parameters:
        - in: path
          name: organizationId
          schema:
            type: string
        - in: query
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
  /admin/enter:
    post:
      description: Handle user's entrance with access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /admin/exit:
    post:
      description: Handle user's exit with access-token
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /admin/stats:
    post:
      description: Daily and live stats for a location
      security:
        - bearerAuthJWT: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                locationId:
                  type: string
              required:
                - locationId
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfStatistics'

  /user/enter:
    post:
      description: Handle self user's entrance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfEntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'

  /triggerReports:
    get:
      description: Triggers reports to be sent for the current hour. Likely to become inaccessible except via cron. This is a GET request with side effects, be cautious!
      responses:
        '200':
          description: Success

  /requestTrace:
    post:
      description: Triggers a contact trace on a user. Likely to become inaccessible except via pubsub
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  properties:
                    data:
                      type: string
                      description: The base64 encoding of "trace-required"
                      enum:
                        - dHJhY2UtcmVxdWlyZWQ=
                    attributes:
                      type: object
                      properties:
                        startTime:
                          type: string
                          description: number of milliseconds since the unix epoch for the beginning of the trace
                        endTime:
                          type: string
                          description: number of milliseconds since the unix epoch for the end of the trace
                        passportStatus:
                          type: string
                          description: status assigned to the user when they triggered the trace
                          enum:
                            - caution
                            - stop
                        userId:
                          type: string
                          description: the id of the user who attested to having symptoms
                        locationId:
                          type: string
                          description: the id of the location the user wanted to enter
                        organizationId:
                          type: string
                          description: the id of the organizaion the location belongs to
                        questionnaireId:
                          type: string
                          description: The id of the questionnaire the user responded to
                        answers:
                          type: string
                          description: The user's JSON-serialized responses

      responses:
        '200':
          description: Success

  /user/exit:
    post:
      description: Handle self user's exit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfEntryOrExitRequest'
      responses:
        '200':
          description: Successfully handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEnterOrExit'
