openapi: 3.0.1
info:
  title: Lookup API
  version: 1.0.0
components:
  schemas:
    Response:
      type: object
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

    Questionnaire:
      type: object
      properties:
        id:
          type: string
        questions:
          type: array
          items:
            type: object

    ResponseOfQuestionnaire:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Questionnaire'
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  succeed,
                  failed,
                  validation_error,
                  internal_server_error,
                  unauthorized,
                  access_denied,
                  resource_not_found,
                ]
            message:
              nullable: true
              type: string

  responses:
    Response:
      description: Default Response wrapper
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
paths:
  /questionnaires/{questionnaireId}:
    get:
      description: Get questionnaire by ID
      parameters:
        - in: path
          name: questionnaireId
          schema:
            type: string
#          required: true
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseOfQuestionnaire'
