export enum RequiredUserPermission {
  SuperAdmin = 'SuperAdmin',
  OPNAdmin = 'OPNAdmin',
  OrgAdmin = 'OrgAdmin',
  RegUser = 'RegUser',
  LabAppointments = 'LabAppointments',
  LabOrOrgAppointments = 'LabOrOrgAppointments',
  LabPCRTestResults = 'LabPCRTestResults',
  LabReceiving = 'LabReceiving',
  LabTransportRunsCreate = 'LabTransportRunsCreate',
  LabTransportRunsList = 'LabTransportRunsList',
  LabTestRunsCreate = 'LabTestRunsCreate',
  LabTestRunsList = 'LabTestRunsList',
  LabSendBulkResults = 'LabSendBulkResults',
  LabSendSingleResults = 'LabSendSingleResults',
  LabDueToday = 'LabDueToday',
  LabAdminToolIDBarcode = 'LabAdminToolIDBarcode',
  LabConfirmResults = 'LabConfirmResults',
  AllowCheckIn = 'AllowCheckIn',
}
