export enum RequiredUserPermission {
  SuperAdmin = 'SuperAdmin',
  OPNAdmin = 'OPNAdmin',
  OrgAdmin = 'OrgAdmin',
  RegUser = 'RegUser',
  LabAppointments = 'LabAppointments',
  LabOrOrgAppointments = 'LabOrOrgAppointments',
  LabPCRTestResults = 'LabPCRTestResults',
  LabReceiving = 'LabReceiving',
  LabTransportRuns = 'LabTransportRuns',
  LabTestRuns = 'LabTestRuns',
  LabSendBulkResults = 'LabSendBulkResults',
  LabSendSingleResults = 'LabSendSingleResults',
  LabDueToday = 'LabDueToday',
  LabAdminToolIDBarcode = 'LabAdminToolIDBarcode',
}
