name: 'Deploy to Cloud Functions'
inputs:
  function_name:
    description: 'Function Name'
    required: true
    default: ""
  secret_file_name:
    description: 'Secret File Nmae'
    required: true
    default: ""
  trigger_topic:
    description: 'Trigger Topic'
    required: true
    default: ""
  region:
    description: 'Resource Region'
    required: true
    default: "northamerica-northeast1"
  

runs:
  using: 'composite'
  steps:
  
  - name: Deploy Modules
    run: |
      echo "Function Name: ${{ inputs.function_name }}"
      EVENT_NAME=${{ github.event_name }}
      EVENT_ACTION=${{ github.event.action }}

      TAG_STRING=$GITHUB_REF
      TAG_NUMBER="${TAG_STRING##*-}"
      GAE_VERSION=${TAG_NUMBER//./-}
      GAE_VERSION_FLAG=""
      
      INFRA_DEV_TAG_REF=refs/tags/infra-dev-
      PREPROD_TAG_REF=refs/tags/preprod-
      PROD_TAG_REF=refs/tags/prod-
      echo "::group::Define Deployment Variables"
      if [[ $GITHUB_REF == 'refs/heads/feature/users-sync' ]]; then
        echo "Deploy to DEV"
        echo "PROJECT_ID=opn-platform-dev" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=dev_service_account" >> $GITHUB_ENV
        echo "PROMOTE_FLAG=--promote" >> $GITHUB_ENV
      elif [[ "$GITHUB_REF" == *"$INFRA_DEV_TAG_REF"* ]]; then
        echo "Deploy to INFRA DEV"
        echo "PROJECT_ID=opn-platform-infra-dev" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=infra_dev_service_account" >> $GITHUB_ENV
        echo "PROMOTE_FLAG=--promote" >> $GITHUB_ENV
        echo "GAE_VERSION_FLAG=--version=$GAE_VERSION" >> $GITHUB_ENV
      elif [[ "$GITHUB_REF" == *"$PREPROD_TAG_REF"* ]]; then
        echo "Deploy to PREPROD"
        echo "PROJECT_ID=opn-platform-preprod" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=preprod_service_account" >> $GITHUB_ENV
        echo "PROMOTE_FLAG=--promote" >> $GITHUB_ENV
      elif [[ "$GITHUB_REF" == *"$PROD_TAG_REF"* ]]; then
        echo "Deploy to PROD"
        echo "PROJECT_ID=opn-platform-ca-prod" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=prod_service_account" >> $GITHUB_ENV
        echo "PROMOTE_FLAG=--no-promote" >> $GITHUB_ENV
      elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
        echo "Deploy to DEV"
        echo "PROJECT_ID=opn-platform-dev" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=dev_service_account" >> $GITHUB_ENV
        echo "PROMOTE_FLAG=--promote" >> $GITHUB_ENV
      else
        echo "Bad Deployment"
        exit 1;
      fi
      echo "::endgroup::"
    shell: bash

  - name: Deploy to GAE
    run: |
      echo "::group::Auth with GCLOUD"
      cat >> service-account.json << EOF
      ${{ env[env.ENV_SERVICE_ACCOUNT] }}
      EOF
      echo "Deploying to: ${{ env.PROJECT_ID }}"
      gcloud auth activate-service-account --key-file=./service-account.json --project=${{ env.PROJECT_ID }}
      rm ./service-account.json
      echo "::endgroup::"
      
      echo "::group::Add Application Environment Variables"
      echo "Writing Environment Variables ${{ inputs.secret_file_name }} to: ./cloud-functions/src/.env"
      gcloud secrets versions access latest --secret=${{ inputs.secret_file_name }} > ./cloud-functions/src/.env
      echo "::endgroup::"

      echo "::group::Install dependencies"
      cd ./services-v2
      npm install
      cd ../cloud-functions/src/${{ inputs.function_name }}
      npm install
      echo "::endgroup::"

      echo "::group::Build"
      npm run build
      echo "::endgroup::"

      echo "::group::Deploy to GAE"
      export TEST=test
      npm run deploy
      echo "::endgroup::"
    shell: bash
