openapi: 3.0.1
info:
  title: Registry Endpoint
  version: 1.0.0

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
            message:
              type: string
          required:
            - status
            - message
      required:
        - error
  responses:
    error:
      description: Default error response with error object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
paths:
  /:
    post:
      description: Get Config
      responses:
        "200":
          description: Successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - complete
                      - error
                  data:
                    type: object
                    properties:
                        updates:
                          type: object
                        services:
                          type: object
                        badgeValidityPeriod:
                          type: object
                        badges:
                          type: object
        default:
          $ref: "#/components/responses/error"