openapi: 3.0.1
info:
  title: Config Endpoint
  version: 1.0.0

components:
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    Error:
      type: object
      additionalProperties: false
      properties:
        error:
          type: object
          additionalProperties: false
          properties:
            status:
              type: integer
            message:
              type: string
          required:
            - status
            - message
      required:
        - error

    QuickbloxResponse: 
      type: object
      additionalProperties: false
      properties:
        status:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              enum:
                - complete
                - error
            message:
              type: string
        data:
          type: object
          additionalProperties: false
          properties:
            provider_id:
              type: number
          required:
            - provider_id

    ResultContentResponse: 
      type: object
      deprecated: false
      additionalProperties: false
      properties:
        legalNotice:
          type: string
        doctorName:
          type: string
        doctorSignature:
          type: string
        resultInfo:
          type: array
          items: 
            type: object
            properties:
              details:
                type: string
              resultType: 
                type: string
                enum:
                  [
                    PresumptivePositive,
                    PreliminaryPositive,
                    Positive,
                    Negative,
                    Pending,
                    Invalid,
                    Inconclusive,
                    Indeterminate,
                  ]
  responses:
    error:
      description: Default error response with error object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
paths:
  /:
    post:
      description: Get Config
      deprecated: true
      responses:
        "200":
          description: Successfully registered
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                    enum:
                      - complete
                      - error
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                        updates:
                          type: object
                          additionalProperties: false
                        services:
                          type: object
                          additionalProperties: false
                        badgeValidityPeriod:
                          type: object
                          additionalProperties: false
                        badges:
                          type: object
                          additionalProperties: false
        default:
          $ref: "#/components/responses/error"

    get:
      description: Get Config
      parameters:
        - in: header
          name: opn-source
          schema:
            type: string
            enum:
              [
                  FH_IOS,
                  FH_Android,
                  OPN_IOS,
                  OPN_Android,
                  Admin_Dashboard,
                  FH_RapidHome_Web
              ]
      responses:
        "200":
          description: Successfully registered
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                    enum:
                      - complete
                      - error
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                        updates:
                          type: object
                          additionalProperties: false
                        services:
                          type: object
                          additionalProperties: false
                        badgeValidityPeriod:
                          type: object
                          additionalProperties: false
                        badges:
                          type: object
                          additionalProperties: false
        default:
          $ref: "#/components/responses/error"
  /config/api/v1/content/result:
    get:
      description: Return Copy for Results Screen
      tags:
        - Content Result
      security:
        - bearerAuthJWT: []
      parameters:
        - in: query
          name: lang
          schema:
            type: string
            enum: 
              [
                en,
                fr
              ]
          required: true
        - in: query
          name: doctor
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Succesfully retrieve transport run list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultContentResponse'

  /config/api/v1/quickblox:
    get:
      description: Return provider id
      tags:
        - Quickblox
      security:
        - bearerAuthJWT: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuickbloxResponse'
