openapi: 3.0.1
info:
  title: Registry Endpoint
  version: 1.0.0
components:
  schemas:
    Response:
      type: object
      properties:
        data:
          nullable: true
          type: object
        status:
          type: object
          properties:
            code:
              type: string
              enum: [
                succeed,
                failed,
                validation_error,
                internal_server_error,
                unauthorized,
                access_denied,
                resource_not_found
              ]
            message:
              nullable: true
              type: string

    Registration:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [admin, user]
        platform:
          type: string
          enum: [ios, android]
        osVersion:
          type: string
        pushToken:
          type: string
          minLength: 5
          maxLength: 40
      required:
        - platform
        - osVersion

    ResponseOfRegistration:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Registration'
        status:
          type: object
          properties:
            code:
              type: string
              enum: [
                succeed,
                failed,
                validation_error,
                internal_server_error,
                unauthorized,
                access_denied,
                resource_not_found
              ]
            message:
              nullable: true
              type: string

  responses:
    Response:
      description: Default Response wrapper
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
paths:
  /user/add:
    post:
      description: Register new app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        "200":
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfRegistration'

  /admin/add:
    post:
      description: Register new app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                registrationToken:
                  type: string
                  minLength: 5
                  maxLength: 40
              required:
                - registrationToken

      responses:
        "200":
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfRegistration'
