name: OPN Services CI Action

on:
  pull_request:
    paths-ignore:
      - 'functional-testing/**'
      - 'cloud-functions/sms-notification/**'
      - '.github/workflows/ci_cloud_function_sms_notification.yml'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm install
          npm run install-all
          npm run lint-all
          npm run build-all
          cd services-v2
          npm install
          npm run lint
          npm run build:all
