name: OPN Services CI Action

on:
  pull_request:
    paths-ignore:
      - 'functional-testing/**'
      - "cloud-functions/sms-notification/**"
      - ".github/workflows/ci_cloud_function_sms_notification.yml"
    branches: 
      - master
      - ci_cd
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run install-all
    - run: npm run lint-all
    - run: npm run build-all
    # - run: npm run test-all
    # - run: lerna run --scope @opn/registry
