name: Deploy Access Service

on:
  push:
    paths:
      - "packages/common/**"
      - "packages/access/**"
      - ".github/workflows/ci_access.yml"
      - ".github/actions/**"
    branches: 
      - develop
    tags:
      - infra-dev-access-*
      - infra-dev-all-*
      - preprod-access-*
      - preprod-all-*
      - prod-access-*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
        
    - uses: ./.github/actions/deploy-gae
      with:
        service_name: "access"
      name: Build & Deploy to GAE
      env:
          dev_service_account: ${{ secrets.DEV_GCP_CLOUDBUILD_SA_KEY}}
          infra_dev_service_account: ${{ secrets.INFRA_DEV_GCP_CLOUDBUILD_SA_KEY}}
          preprod_service_account: ${{ secrets.PREPROD_GCP_CLOUDBUILD_SA_KEY }}
          prod_service_account: ${{ secrets.PROD_GCP_CLOUDBUILD_SA_KEY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}