name: CloudFunctionSMSNotification

on:
  push: 
    paths:
      - "cloud-functions/src/hl7-egress/**"
      - ".github/workflows/ci_cloud_function_hl7_egress.yml"
      - ".github/actions/deploy-functions/**"
    branches: 
      - master
      - feature/hl7-egress

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-functions
      with:
        function_name: "hl7-egress"
        secret_file_name: "CF_HL7_EGRESS"
      name: Build & Deploy to Cloud Functions
      env:
          dev_service_account: ${{ secrets.DEV_GCP_CLOUDBUILD_SA_KEY}}
          infra_dev_service_account: ${{ secrets.INFRA_DEV_GCP_CLOUDBUILD_SA_KEY}}
          preprod_service_account: ${{ secrets.PREPROD_GCP_CLOUDBUILD_SA_KEY }}
          prod_service_account: ${{ secrets.PROD_GCP_CLOUDBUILD_SA_KEY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    