name: CloudFunctionSMSNotification

on:
  pull_request: 
    paths:
      - "cloud-functions/sms-notifications/**"
      - ".github/workflows/ci_cloud_function_sms_notification.yml"
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        cd cloud-functions/sms-notifications
        pwd
        gcloud functions deploy sms-notification --entry-point sendSMS
    