name: OPN Enterprise Service CD Action

on:
  push:
    paths:
      - "packages/common/**"
      - "packages/enterprise/**"
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Setup GCloud
      if: github.ref == 'refs/heads/development'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.DEV_GCP_CLOUDBUILD_SA_KEY }}
    - run: npm install
    - run: npm run install-all
    - run: npm run lint-all
    # - run: npm run test-all
    - run: npm run cd-build-enterprise
    - name: Create Environment Parameters
      if: github.ref == 'refs/heads/development'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./packages/enterprise/dist/common/.env
        contents: |
          # Environment Config for Dev Access
          # Firebase:
          FIREBASE_ADMINSDK_SA=${{ secrets.DEV_GCP_FIREBASEADMIN_SA_KEY_NOCR }}

          # Firebase Auth Sign App Code Settings:
          AUTH_EMAIL_SIGNIN_LINK=https://devopn.page.link/auth-finished
          AUTH_EMAIL_SIGNIN_IOS=com.opentech.stayopn
          AUTH_EMAIL_SIGNIN_ANDROID=com.stayopn.debug
          AUTH_EMAIL_SIGNIN_DOMAIN=devopn.page.link

          # Email / SMTP Provider:
          EMAIL_PROVIDER_API_KEY=${{ secrets.DEV_EMAILPROVIDER_KEY }}
          EMAIL_PROVIDER_API_URL=https://api.sendinblue.com/v3/smtp/email

          # Links
          LINK_PRIVACYPOLICY=https://dev.pages.opnte.ch/privacy-policy.html
          LINK_TERMSOFSERVICE=https://dev.pages.opnte.ch/terms-of-service.html

          # Domains 
          DOMAIN_ACCESS=https://access-staging-dot-opn-platform-dev.nn.r.appspot.com/
          DOMAIN_ENTERPRISE=https://enterprise-staging-dot-opn-platform-dev.nn.r.appspot.com/
          DOMAIN_LOOKUP=https://lookup-staging-dot-opn-platform-dev.nn.r.appspot.com/
          DOMAIN_PASSPORT=https://passport-staging-dot-opn-platform-dev.nn.r.appspot.com/
          DOMAIN_REGISTRY=https://registry-staging-dot-opn-platform-dev.nn.r.appspot.com/

          # Features
          FEATURE_CREATE_TOKEN_PERMISSIVE_MODE=enabled
        write-mode: overwrite
    - run: npm run cd-deploy-enterprise
    - run: npm run cd-deploy-apidocs
    - name: Let Slack know
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            username: 'action-slack',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `Latest Build to succeeded. Check API Docs: https://apidocs-dot-opn-platform-dev.nn.r.appspot.com`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}