name: Integration Test (2AM)
on:
  schedule:
   - cron: "0 3 * * *"
  push:
    paths:
      - "packages/common/**"
      - "packages/reservation/**"
      - ".github/workflows/**"
      - ".github/actions/**"
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop

    - uses: ./.github/actions/integration-tests
      name: Run Integration Tests
      env:
          infra_dev_service_account: ${{ secrets.INFRA_DEV_GCP_CLOUDBUILD_SA_KEY}}
    - uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
        title: 'Integration Test Run'
        text_on_success: 'Integration Tests Succeed'
        text_on_fail: 'Integration Tests Failed'
        text_on_cancel: 'Integration Tests Cancel'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, but GitHub should automatically supply
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INTEGRATION_TEST_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
