name: OPN Services Integration Test
on:
  push:
    paths:
      - "packages/common/**"
      - "packages/reservation/**"
      - ".github/workflows/**"
      - ".github/actions/**"
    branches: 
      - ci_cd

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ci_cd
        
    - uses: ./.github/actions/integration-tests
      name: Run Integration Tests
      env:
          infra_dev_service_account: ${{ secrets.INFRA_DEV_GCP_CLOUDBUILD_SA_KEY}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_INTEGRATION_TEST_URL }}
    - uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
        title: 'Nightly Failure'
        text: 'Integration Tests Failed'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, but GitHub should automatically supply
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INTEGRATION_TEST_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
