name: Integration Test (2AM)
on:
  schedule:
   - cron: "0 3 * * *"
  push:
    paths:
      - "packages/common/**"
      - "packages/reservation/**"
      - ".github/workflows/**"
      - ".github/actions/**"
    branches: 
      - master
      - feature/integration-tests-fresh
    tags:
      - preprod-*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/integration-tests-fresh
        
    - uses: ./.github/actions/integration-tests
      name: Run Integration Tests
      env:
          infra_dev_service_account: ${{ secrets.INFRA_DEV_GCP_CLOUDBUILD_SA_KEY}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_INTEGRATION_TEST_URL }}
